### ISSUE TITLE
这个项目不完整，英雄未定义

### ISSUE THREAD

**Issue by ghost** [sumneko/war3-lua-map#6]
Error: lua\script\game\init.lua:4: attempt to index a nil value (global 'ac')

**Comment by sumneko** [comment]
你需要拉子模块

**Comment by ghost** [comment]
w3x3lni/plugin/import文件夹是什么作用的，只是负责初始化？

**Comment by ghost** [comment]
Lua 5.3
图标    {skill|@商店物品栏-2} -> {unit|商店|1048672}
图标    {skill|@商店物品栏-3} -> {unit|商店|1048672}
图标    {skill|@商店物品栏-4} -> {unit|商店|1048672}
图标    {skill|@商店物品栏-5} -> {unit|商店|1048672}
图标    {skill|@商店物品栏-6} -> {unit|商店|1048672}
图标    {skill|@商店物品栏-7} -> {unit|商店|1048672}
图标    {skill|@商店物品-8} -> {unit|商店|1048672}
图标    {skill|@商店物品-9} -> {unit|商店|1048672}
图标    {skill|@商店物品-10} -> {unit|商店|1048672}
开始执行游戏逻辑lua脚本
package.path?.lua;scripts\?.lua;scripts\?\init.lua;w3x2lni\plugin\import\scripts\?.lua;w3x2lni\plugin\import\scripts\?\init.lua;F:\dafuwong\war3-lua-map\scripts\?.lua;F:\dafuwong\war3-lua-map\scripts\?\init.lua;F:\dafuwong\war3-lua-map\w3x2lni\plugin\import\scripts\?.lua;F:\dafuwong\war3-lua-map\w3x2lni\plugin\import\scripts\?\init.lua;script\?.lua
---------------------------------------
lua\script\skill\测试技能.lua:6: attempt to index a nil value (local 'mt')

stack traceback:
        ...ar3-lua-map\w3x2lni\plugin\import\scripts\ac\runtime.lua:18: in metamethod '__newindex'
        lua\script\skill\测试技能.lua:6: in main chunk
        [C]: in function 'require'
        lua\script\skill\init.lua:17: in main chunk
        [C]: in function 'require'
        lua\base.lua:54: in main chunk
        [C]: in function 'require'
---------------------------------------

**Comment by oxpy** [comment]
是少了哪一步么
