### ISSUE TITLE
请大神帮助

### ISSUE THREAD

**Issue by ghost** [sumneko/war3-lua-map#7]
string "module 'slk'"]  : attempt to call a nil value
这种报错可能是什么原因？

**Comment by ghost** [comment]
print(jass.slk)  打印是nil

**Comment by sumneko** [comment]
使用 YDWE 1.32 启动魔兽

**Comment by ghost** [comment]
我这是本地编译的YDWE，不能用么

**Comment by ghost** [comment]
我用的是master分支编译的，可以用么

**Comment by ghost** [comment]
请大神说明一下这个slk打印为nil的原因，我好修改一下代码

**Comment by sumneko** [comment]
不知道

**Comment by ghost** [comment]
YDWE的哪个版本是默认导入全部jass 的lua 库

**Comment by sumneko** [comment]
不记得了，我当时用的 YDWE 1.32 最新版本

**Comment by ghost** [comment]
大神指导一下，相关代码在哪个文件或者子工程里？我看下代码

**Comment by sumneko** [comment]
https://github.com/actboy168/YDWE/blob/master/Development/Plugin/Warcraft3/yd_lua_engine/lua_engine/libs_slk.cpp

**Comment by ghost** [comment]
谢谢大神回复。
1.32 版本为什么luaengine.dll没有加载呢
